{
 "title": "project",
 "time": { "from": "now/fy", "to": "now/fy" },
 "templating": {
  "list": [
   {
    "name": "tickers",
    "query": "from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\")\n  |> keep(columns: [\"ticker\"])\n  |> distinct(column: \"ticker\")\n  |> map(fn: (r) => ({r with _value: r.ticker}))\n  |> keep(columns: [\"_value\"])\n  |> sort(columns: [\"_value\"])\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Most Active Stocks among $tickers (by Volume) ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Volume\" and contains(value: r.ticker, set: ${tickers:json}))\n  |> group(columns: [\"ticker\"])\n  |> sum(column: \"_value\")  // Sum of volume for each stock\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 5)  // Top 5 most active stocks"
    }
   ]
  },
  {
   "title": "Price and Moving Average of $tickers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) // Replace with your desired time range\n  |> filter(fn: (r) => \n      r._measurement == \"stock_prices\" and \n      r._field == \"Close\" and \n      contains(value: r.ticker, set: ${tickers:json})\n  )\n  |> map(fn: (r) => ({\n      r with \n      price: float(v: r._value) // Duplicate the original price into a new column\n  }))\n  |> group(columns: [\"ticker\"]) // Group by ticker to calculate moving average per ticker\n  |> movingAverage(n: 5) // Replace 5 with your desired window size\n  |> map(fn: (r) => ({\n      ticker: r.ticker,\n      _time: r._time,\n      price: r.price, \n      moving_average: r._value \n  }))\n"
    }
   ]
  },
  {
   "title": "Correlation b/w MSFT and AAPL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// Fetch data for stock AAPL\naapl = from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Close\" and r.ticker == \"AAPL\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"AAPL\"})\n\naapl_m = \n  aapl\n  |> mean(column: \"AAPL\")\n\naapl_std = \n  aapl\n  |> stddev(column: \"AAPL\")\n  \n\naapl_stddev = aapl_std |> findRecord(fn: (key) => true, idx: 0)\naapl_mean = aapl_m |> findRecord(fn: (key) => true, idx: 0)\n\nmsft = from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Close\" and r.ticker == \"MSFT\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> rename(columns: {_value: \"MSFT\"})  \n\n\n\nmsft_m = \n  msft\n  |> mean(column: \"MSFT\")\n\nmsft_std = \n  msft\n  |> stddev(column: \"MSFT\")\n  \n\nmsft_stddev = msft_std |> findRecord(fn: (key) => true, idx: 0)\nmsft_mean = msft_m |> findRecord(fn: (key) => true, idx: 0)\n\njoined = join(tables: {a: aapl, b: msft}, on: [\"_time\"])\n\ncorrelation = \n  joined\n  |> map(fn: (r) => ({\n      r with\n      covar: (r.AAPL - aapl_mean.AAPL) * (r.MSFT - msft_mean.MSFT)\n  }))\n\n  |> mean(column: \"covar\")\n  |> map(fn: (r) => ({\n      r with\n      correlation: r.covar / (aapl_stddev.AAPL * msft_stddev.MSFT)\n  }))\n  |> keep(columns: [\"correlation\"])\n\n\nyield correlation"
    }
   ]
  },
  {
   "title": "Close price of ${tickers}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and contains(value: r.ticker, set: ${tickers:json}))\n  |> filter(fn: (r) => r._field == \"Close\")\n  \n"
    }
   ]
  },
  {
   "title": "Continuous Downturn ",
   "type": "piechart",
   "description": "Identifies companies with the most consecutive days of price drops",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart)  // Last 7 days\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Close\" and contains(value: r.ticker, set: ${tickers:json}))\n  |> group(columns: [\"ticker\"])\n  |> sort(columns: [\"_time\"])\n  |> difference(columns: [\"_value\"], nonNegative: false)  // Calculate price differences\n  |> map(fn: (r) => ({\n      r with is_downturn: if r._value < 0 then 1 else 0  // Mark downturns as 1\n  }))\n  |> cumulativeSum(columns: [\"is_downturn\"])  // Cumulative count of downturns\n  |> group(columns: [\"ticker\"], mode: \"by\")\n  |> max(column: \"is_downturn\")  // Maximum cumulative downturn count per stock\n  |> keep(columns: [\"ticker\", \"is_downturn\"])\n  |> sort(columns: [\"is_downturn\"], desc: true)"
    }
   ]
  },
  {
   "title": "Stock Price Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart)  \n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Close\" and contains(value: r.ticker, set: ${tickers:json}))\n  |> group(columns: [\"ticker\"])  // Group by stock to separate lines\n  |> sort(columns: [\"_time\"])  // Ensure data is ordered by time\n  |> keep(columns: [\"_time\", \"ticker\", \"_value\"])  // Only keep relevant columns"
    }
   ]
  },
  {
   "title": "Percentage Change for $tickers",
   "type": "timeseries",
   "description": "Difference in values for close prices",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Close\" and contains(value: r.ticker, set: ${tickers:json}))\n  |> group(columns: [\"ticker\"])\n  |> sort(columns: [\"_time\"])\n  |> difference(columns: [\"_value\"], nonNegative: false)\n  |> map(fn: (r) => ({\n      r with \n      Close_price: float(v: r._value)  // Create a new column from _value (close price)\n  }))\n  |> keep(columns: [\"Close_price\", \"_time\", \"ticker\"])"
    }
   ]
  },
  {
   "title": "Leader Companies",
   "type": "barchart",
   "description": "This query calculates avg stock price for each company and identifies by leader. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart)  \n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Close\" and r.ticker != \"BRK-A\" and r.ticker != \"BKNG\")\n  |> group(columns: [\"ticker\"])\n  |> mean(column: \"_value\")\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)  // Sort by average price\n  |> keep(columns: [\"ticker\", \"_value\"])\n  |> limit(n: 5)"
    }
   ]
  },
  {
   "title": "Seasonality",
   "type": "timeseries",
   "description": "This query calculates the monthly averages of stock prices for each company",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart)  // Last 1 year\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Close\" and contains(value: r.ticker, set: ${tickers:json}))\n  |> group(columns: [\"ticker\"])\n  |> aggregateWindow(every: 1mo, fn: mean, createEmpty: false)  // Monthly averages\n  |> keep(columns: [\"_time\", \"ticker\", \"_value\"])"
    }
   ]
  },
  { "title": "Latest News", "type": "news", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 } },
  {
   "title": "Latest Price of $tickers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and contains(value: r.ticker, set: ${tickers:json}))\n  |> filter(fn: (r) => r._field == \"Close\")\n  |> group(columns: [\"ticker\"])\n  |> window(period: 1d)\n  |> last()\n  |> group(columns: [\"ticker\"])\n  |> duplicate(column: \"_value\", as: \"latest_price\")\n  |> difference(nonNegative: false, columns: [\"_value\"])\n  |> rename(columns: { \"_value\" : \"price_difference\"})\n  |> drop(columns: [\"_start\", \"_stop\"])\n  |> last(column: \"price_difference\")\n"
    }
   ]
  },
  {
   "title": "Volume vs Price action over Last Week",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "\npriceChange = from(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\")\n  |> filter(fn: (r) => r._field == \"Open\" or r._field == \"Close\")\n  |> group(columns: [\"ticker\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      ticker: r.ticker,\n      price_change: ((r.Close - r.Open) / r.Open) * 100.0,\n      ticker_data: r.ticker\n  }))\n  |> mean(column: \"price_change\")\n  \n\n// Calculate mean Volume\nmeanVolume = from(bucket: \"stock_data_bucket\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Volume\")\n  |> group(columns: [\"ticker\"])\n  |> mean(column: \"_value\")\n  |> rename(columns: {_value: \"mean_volume\"}) \n  |> map(fn: (r) => ({\n      ticker: r.ticker,\n      mean_volume: r.mean_volume,\n      ticker_data: r.ticker\n  }))\n\njoin(\n  tables: {priceChange: priceChange, meanVolume: meanVolume},\n  on: [\"ticker\"]\n)\n\n"
    }
   ]
  },
  {
   "title": "Fear v Greed Index",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental\"\n\n// Define the lookback period and moving average windows\nlookback = -125d\npriceMaWindow = 5\nmomentumMaWindow = 14\n\nprocessed = \n  from(bucket: \"stock_data_bucket\")\n    |> range(\n        start: experimental.subDuration(d: lookback, from: v.timeRangeStart), \n        stop: v.timeRangeStop\n    )\n    |> filter(fn: (r) => r._measurement == \"stock_prices\" and (r._field == \"Close\" or r._field == \"Volume\"))\n    |> map(fn: (r) => ({\n        r with \n        _value: float(v: r._value) // Explicitly cast numeric fields to float\n    }))\n    |> group(columns: [\"ticker\"]) // Group by ticker to avoid schema collisions\n    |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") // Pivot to have Close and Volume as columns\n    |> map(fn: (r) => ({\n        r with \n        Close_price: float(v: r.Close) // Duplicate the original price into a new column\n    }))\n    |> rename(columns: {\"Close\": \"_value\"})\n    |> movingAverage(n: priceMaWindow)\n    |> rename(columns: {_value: \"Close_MA\"}) // Rename moving average to Close_MA\n    \n    |> map(fn: (r) => ({\n        r with \n        price_momentum: if r.Close_MA == 0.0 then 0.0 else (r.Close_price - r.Close_MA) / r.Close_MA * 100.0 // Calculate price momentum as % difference\n    }))\n\n    // Calculate the percentage change in volume (volume strength)\n    |> map(fn: (r) => ({\n        r with \n        Volume_copy: float(v: r.Volume) // Duplicate the original price into a new column\n    }))\n    \n    |> difference(columns: [\"Volume\"])\n    |> map(fn: (r) => ({\n        r with \n        volume_strength: if r.Volume_copy == 0.0 then 0.0 else (- r.Volume / r.Volume_copy) * 100.0 // Volume strength as % change\n    }))\n\nsmoothed = \n  processed\n  |> keep(columns: [\"_time\", \"volume_strength\", \"ticker\"])\n  |> map(fn: (r) => ({\n      r with \n      volume_strength_copy: float(v: r.volume_strength) // Duplicate the original price into a new column\n  }))\n  |> rename(columns: {\"volume_strength_copy\": \"_value\"})\n  |> drop(columns: [\"volume_strength\"])\n  |> movingAverage(n: momentumMaWindow)\n  |> rename(columns: {\"_value\": \"volume_strength_smoothed\"}) // Rename smoothed value for volume strength\n  \n  \njoined = \n  join(\n    tables: {processed: processed, smoothed: smoothed},\n    on: [\"_time\", \"ticker\"]\n  )\n\nstats = \n  joined\n  |> group()\n  |> range(start: v.timeRangeStart)\n  |> reduce(\n      identity: {min_pm: 1000.0, max_pm: -1000.0, min_vs: 1000.0, max_vs: -1000.0},\n      fn: (r, accumulator) => ({\n          min_pm: if r.price_momentum < accumulator.min_pm then r.price_momentum else accumulator.min_pm,\n          max_pm: if r.price_momentum > accumulator.max_pm then r.price_momentum else accumulator.max_pm,\n          min_vs: if r.volume_strength_smoothed < accumulator.min_vs then r.volume_strength_smoothed else accumulator.min_vs,\n          max_vs: if r.volume_strength_smoothed > accumulator.max_vs then r.volume_strength_smoothed else accumulator.max_vs\n      })\n  )\n\nmin_max = stats |> findRecord(fn: (key) => true, idx: 0)\n\nnormalized = \n  joined\n    |> map(fn: (r) => ({\n      r with \n      normalized_vs: (r.volume_strength_smoothed - min_max.min_vs) / (min_max.max_vs - min_max.min_vs),\n      normalized_pm: (r.price_momentum - min_max.min_pm) / (min_max.max_pm - min_max.min_pm)\n    }))\n\nfear_and_greed_index = \n  normalized\n  |> map(fn: (r) => ({\n      r with \n      fear_greed_index: 50.0 + ((r.normalized_pm + r.normalized_vs) / 2.0) * 50.0\n    }))\n  |> group()\n  |> mean(column: \"fear_greed_index\")\n\nyield fear_and_greed_index\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"stock_data_bucket\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"stock_prices\" and r._field == \"Close\" and contains(value: r.ticker , set: ${tickers:json}))\n  |> group(columns: [\"ticker\"])\n  |> sort(columns: [\"_time\"])\n  |> difference(columns: [\"_value\"], nonNegative: false)"
    }
   ]
  }
 ]
}